language: python
python: "3.5"
install:
  - pip install coveralls
  - pip install termcolor
#  - python termcolor-1.1.0/setup.py install
#script: pytest
script: coverage run -m unittest
after_success: coveralls
