language: python
python: "3.5"
install:
  - pip install coveralls
  - sudo pip install termcolor
  - sudo python setup.py install
#script: pytest
script: coverage run test_rpn.py test
after_success: coveralls
